NAME: 20241215-vlnce-rp-noRNN-DPDec12Step20-txtLayer6-txtQformer-stackRGB16-ClsFree0.25-bs80x3-lr2e-4-lrCos
TRAINER_NAME: dagger_diffusion_policy # dagger / recollect_trainer
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
TORCH_GPU_IDS: [0,1,2]
# SIMULATOR_GPU_IDS: [0]
# TORCH_GPU_ID: 1
# TORCH_GPU_IDS: [2]

NUM_ENVIRONMENTS: 4
# TENSORBOARD_DIR: data/tensorboard_dirs/*name
TENSORBOARD_DIR: data/checkpoints/*name
CHECKPOINT_FOLDER: data/checkpoints/*name/ckpts
EVAL_CKPT_PATH_DIR: data/checkpoints/*name/ckpts
# EVAL_CKPT_PATH_DIR: /ssd/wangliuyi/code/w61_grutopia/data/checkpoints/20241215-vlnce-rp-noRNN-DPDec12Step20-txtLayer6-txtQformer-stackRGB16-ClsFree0.25-bs80x3-lr2e-4-lrCos/ckpts/ckpt.38.pth
LOG_DIR: data/checkpoints/*name/logs
RESULTS_DIR: data/checkpoints/*name/evals

VIDEO_OPTION: true # -1 / true
VIDEO_DIR: data/checkpoints/*name/videos

SEED: 0
DDP:
  use: true
  use_dp: false # true for data parallel, false for DDP
  backend: nccl
  seed: 0
  fp16: False
  n_workers: 8
  find_unused_parameters: true
  local_rank: 0 

  node_rank: 0
  world_size: 4

EVAL:
  USE_CKPT_CONFIG: False
  SAVE_RESULTS: True
  # SPLIT: [val_seen, val_unseen]
  SPLIT: [train]
  EPISODE_COUNT: -1
  MAX_STEPS: 195
  train_eval_interval: 100
  ACTION: xyyaw # descrete or xyyaw

  # for xyyaw
  success_distance: 3.0
  stop_x_threshold: 1e-2
  stop_y_threshold: 1e-2
  stop_yaw_threshold: 1e-2

  rotation_threshold: 1e-2

  # for dynamic len_traj_act
  use_dynamic_len_traj_act: true
  min_len_traj_act: 3
  max_len_traj_act: 8
  min_displacement: 0.15

  distance_threshold: 1.5
  num_sample: 1
  auto_remove: false

  start_eval_epoch: -1
  
  # stop settings
  stop_mode: progress # progress / distance
  distance_threshold: 1.5
  pm_threshold: 0.90

  # for isaac-sim envs
  sim_cfg_file: vln/configs/sim_cfg_policy_eval.yaml
  vln_cfg_file: vln/configs/vln_cfg_policy_eval.yaml
  step_interval: 80 # the same in data sampling

  # len_traj_act
  len_traj_act: 2

IL:
  epochs: 60
  batch_size: 80
  lr: 2e-4
  
  save_interval_epochs: 2
  save_interval_steps: -1
  save_filter_frozen_weights: true # only save the learnable weights!
  load_from_ckpt: true
  ckpt_to_load: /ssd/wangliuyi/code/w61_grutopia/data/checkpoints/20241215-vlnce-rp-noRNN-DPDec12Step20-txtLayer6-txtQformer-stackRGB16-ClsFree0.25-bs80x3-lr2e-4-lrCos/ckpts/ckpt.38.pth
  load_from_pretrain: false

  dataset_root_dir: data/datasets/R2R_VLNCE_v1-3_corrected

  camera_name: 'pano_camera_0'
  Filter_failure: 
    use: true # drop the failure cases
    min_rgb_nums: 15 # the item that is fewer than this number would be dropped.

  analysis_time: False # analysis the processing time for each module

  lr_schedule:
    use: true
    type: "cosine" # 可选 cosine/step/linear
    warmup_epochs: 5
    warmup_factor: 0.1
    decay_factor: 0.1
    decay_epochs: [30, 45] # 用于step scheduler
    min_lr: 1e-5

  DAGGER:
    iterations: 5
    full_size: 10819
    update_size: 5000
    p: 0.9
    preload_lmdb_features: true # !IMPORTANT!
    # lmdb_features_dir: data/sample_episodes/20241207_sample_episodes/sample_data.lmdb
    lmdb_features_dir: data/sample_episodes/20241207_sample_episodes_processed/sample_data.lmdb
    # lmdb_features_dir: /dev/shm/sample_data.lmdb # For slurm
    lmdb_features_dagger_update_dir: data/sample_episodes/20241207_sample_episodes_processed/sample_data.lmdb
    pre_extract_img_features: true
    denoise_action: false # For debug!!!
    lmdb_save_episode_id: true
    save_img_raw: false
    sample_action_mode: policy # gt / policy / negative_sampling

    recollect_first: false

MODEL:
  policy_name: DP_noRNN_Policy # CMA_DP_Policy / CMA_DP_ImgMultiPatch_Policy / DP_noRNN_Policy

  # training settings
  learn_angle: true # true: [delta_x, delta_y, delta_yaw] / false: [r, theta]
  use_iw: false
  len_traj_act: 4

  TEXT_ENCODER:
    load_model: true
    max_length: 248
    update_text_encoder: false
    
    # model settings
    type: clip-long # roberta
    model_name: clip-long # meter
    model_path: data/pretrained/clip-long/longclip-B.pt # data/pretrained/meter/meter_clip16_224_roberta_pretrain.ckpt
    num_l_layers: 12 # before: 6
    hidden_size: 512
    vocab_size: 50265
    embedding_size: 512

    # text Q-former
    use_qformer: True
    q_former_length: 20

  IMAGE_ENCODER:
    img_stack_nums: 16 # the history images for inputs
    use_stack: true 
    dropout: 0.1
    use_env_drop: true
    env_drop: 0.1

    RGB:
      load_model: true
      update_rgb_encoder: False

      # model settings
      model_name: clip-long # clip-vit-base-patch32
      model_path: data/pretrained/clip-long/longclip-B.pt # data/pretrained/clip-vit-base-patch32
      rgb_proj: false # 768 -> 512?
      feature_dim: 768
      projection_dim: 512

      # img_mod
      img_mod: multi_patches_avg_pooling # cls / multi_patches_avg_pooling
      multi_patches_num: 5
  
    DEPTH:
      load_model: True
      update_depth_encoder: True

      # model settings
      bottleneck: resnet # TAC
      model_name: openai/clip-vit-base-patch32
      model_path: data/pretrained/TAC/tac_depth_encoder.pth
      feature_dim: 768
      projection_dim: 512

      # for Resnet
      cnn_type: VlnResnetDepthEncoder
      output_size: 128
      ddppo_checkpoint: data/ddppo-models/gibson-4plus-mp3d-train-val-test-resnet50.pth
      backbone: resnet50

  CROSS_MODAL_ENCODER:
    load_model: False
    input_type: 3
    num_x_layers: 2
    hidden_size: 512
    num_attention_heads: 8

    txt_to_img: True
    txt_to_img_layer: 1
  
  STATE_ENCODER:
    hidden_size: 512
    rnn_type: GRU
    num_layers: 1

    rgb_depth_embed_method: flat # for multi_patches_avg_pooling. flat / first

  Diffusion_Policy:
    type: transformer # resnet_unet

    # scheduler
    scheduler: DDPM # DDPM / DDIM

    # pred_type
    pred_type: epsilon # epsilon / sample

    # classifier-free guidance
    use_cls_free_guidance: true
    cls_free_guidance_scale: 0.8
    cls_mask_ratio: 0.25
    random_mask_rgb: False
    random_mask_instr: True

    # distance bounds for distance and action and distance predictions 
    distance:
      min_dist_cat: 0
      max_dist_cat: 20
    action:
      min_dist_cat: 3
      max_dist_cat: 20

    action_stats:
      # min: [-0.25, -0.25, -0.27] # [min_dx, min_dy, min_dyaw]
      # max: [0.25, 0.25, 0.27] # [max_dx, max_dy, max_dyaw]
      min: [-0.5, -0.5, -0.6] # [min_dx, min_dy, min_dyaw]
      max: [0.5, 0.5, 0.6] # [max_dx, max_dy, max_dyaw]

    waypoint_spacing: 1
    metric_waypoint_spacing: 1
    negative_mining: False

    # diffusion model params
    num_diffusion_iters: 100
    context_size: 1
    context_type: "temporal"

    # for resnet_unet
    encoding_size: 512
    diffusion_step_embed_dim: 256
    down_dims: [128,256,512]
    cond_predict_scale: false
    use_local_cond: true

    # for transformer
    transformer_n_cond_layers: 0
    transformer_n_layers: 8
    transformer_encoding_size: 512
    # transformer_n_head: 8
    transformer_p_drop_emb: 0
    cond: 'v2_Fullinstr' # rnn_instr / rnn_instr_vis / rnn_Fullinstr_vis / rnn_Fullinstr / v2_instr / v2_Fullinstr
    txt_len: 20 # use for v2_Fullinstr

    # action output params
    len_traj_pred: 8

  DISTANCE_PREDICTOR:
    use: false
    normalize: false
  
  IMU_ENCODER:
    input_size: 3
    encoding_size: 512
    use: true

    to_local_coords: true
  
  PREV_ACTION_ENCODER:
    encoding_size: 512
  
  PROGRESS_MONITOR:
    use: true

  STOP_PROGRESS_PREDICTOR:
    use: True

  STEP_ENCODER:
    encoding_size: 512
    use: true
    max_steps: 500

  LOSS:
    alpha: 0.0001
    dist_scale: 1
  
  LORA:
    add_for_instruction_encoder: False
    add_for_rgb_encoder: False
    add_for_depth_encoder: False

    lora_r: 8
    lora_alpha: 16
    lora_dropout: 0.05
    lora_start_layer: 6 # from this layer to add lora layers
    lora_query: True
    lora_key: False
    lora_value: False
    lora_projection: False
    lora_mlp: False
    lora_head: False