simulator:
  physics_dt: 1/240
  rendering_dt: 1/240

tasks:
- type: "SingleInferenceTask"
  name: "vln"
  scene_asset_path: ""
  scene_scale: [1, 1, 1]
  env_num: 1
  offset_size: 0.0
  robots:
  - name: robot_test
    prim_path: "/CY"
    type: "CylinderRobot"
    position: [0, 0, 0]
    # scale: [0.22, 0.57, 1.7] # this mimics the scale of H1
    scale: [1, 1, 1]
    orientation: [0,0,0,0]
    sensor_params:
    - name: "camera_tp"
      enable: true
      size: [512, 512]
    - name: "camera_front"
      enable: true
      size: [512, 512]
    - name: "camera_behind"
      enable: true
      size: [512, 512]
    - name: "camera_left"
      enable: true
      size: [512, 512]
    - name: "camera_right"
      enable: true
      size: [512, 512]
