simulator:
  physics_dt: 1/240
  rendering_dt: 1/240

tasks:
- type: "SingleInferenceTask"
  name: "vln"
  scene_asset_path: ""
  scene_scale: [1, 1, 1]
  env_num: 1
  offset_size: 0.0
  light_on: true
  robots:
  # - name: robot_test
  #   prim_path: "/CY"
  #   type: "CylinderRobot"
  #   position: [0, 0, 0]
  #   scale: [0.22, 0.57, 1.3] # this mimics the scale of H1
  #   # scale: [1, 1, 1]
  #   orientation: [0,0,0,0]
  #   sensor_params:
  #   - name: "camera_tp"
  #     enable: true
  #     size: [512, 512]
  #   - name: "camera_front"
  #     enable: true
  #     size: [512, 512]
  #   - name: "camera_behind"
  #     enable: true
  #     size: [512, 512]
  #   - name: "camera_left"
  #     enable: true
  #     size: [512, 512]
  #   - name: "camera_right"
  #     enable: true
  #     size: [512, 512]
  - name: h1
    prim_path: "/World/h1"
    type: "HumanoidRobot"
    position: [0, 0, 0]
    scale: [1, 1, 1]
    orientation: [0,0,0,0]
    controller_params:
    - name: "move_by_speed"
    - name: "joint_controller"
    - name: "move_to_point"
    - name: "move_along_path"
    - name: "rotate"
    - name: "move_with_keyboard"
    - name: "web_chat"
    - name: "stand_still"
    sensor_params:
    # - name: "camera_front"
    #   enable: true
    #   size: [640, 480]
    # - name: "camera_left"
    #   enable: true
    #   size: [640, 480]
    # - name: "camera_right"
    #   enable: true
    #   size: [640, 480]
    # - name: "camera_behind"
    #   enable: true
    #   size: [640, 480]
    - name: "pano_camera_0"
      enable: true
      size: [640, 480]
    - name: "pano_camera_45"
      enable: true
      size: [640, 480]
    - name: "pano_camera_90"
      enable: true
      size: [640, 480]
    - name: "pano_camera_135"
      enable: true
      size: [640, 480]
    - name: "pano_camera_180"
      enable: true
      size: [640, 480]
    - name: "pano_camera_225"
      enable: true
      size: [640, 480]
    - name: "pano_camera_270"
      enable: true
      size: [640, 480]
    - name: "pano_camera_315"
      enable: true
      size: [640, 480]
