datasets:
  base_data_dir: "../VLN/VLNCE/R2R_VLNCE_v1-3"
  mp3d_data_dir: "../Matterport3D/data/v1/scans"
  mp3d_category_file: "vln/data/mappings/category_mapping.tsv"
  mp3d_mpcat40_file: "vln/data/mappings/mpcat40.tsv"
  splits:
    - train
    - val_seen
    - val_unseen
    # - test

settings:
  mode: "sample_episodes_multiprocess"
  # mode: "sample_episodes_reset_scans" # sample_episodes_reset_scans
  batch_size: 1
  action: "move_along_path"
  # action: "oracle_move_along_path"
  check_and_reset_robot: true
  use_llm: true
  sample_camera_list:
    - pano_camera_0
  camera_data_type:
    - rgba
    - depth
    - camera_params
  max_step: 20000
  force_sample: false
  force_sample_scan: false
  filter_stairs: true
  sample_env_flow: true # allow the env flow
  num_workers: 3

sample_episodes:
  step_interval: 40

robots:
  - name: "CylinderRobot"
    z_offset: 0.7 # !!!
  - name: "HumanoidRobot"
    z_offset: 0.975 # !!! 1.05
  
maps:
  robot_z: [0.1, 1.7]  # Robot's height range on the Z-axis
  global_robot_z: [0, 1.7]
  agent_radius: 0.25 # Robot's radius (original: 0.25)
  voxel_size: 0.1  # Size of a voxel (original: 0.05)
  add_dilation: true # Add dilation to the map
  dilation_iterations: 2 # Number of dilation iterations
  quadtree_config:
    width: 50 # Quadtree map size
    height: 50
    global_width: 30 # for global map
    global_height: 30
    max_depth: 8  # Maximum depth of the quadtree
    threshold: 1  # Threshold for node splitting  
  global_topdown_config:
    width: 500
    height: 500
    aperture: 500
    camera_transform_height: 0.8
    voxel_size: 0.1
    
planners:
  method: "a_star" # The method used for planning (a_star or rrt_star)
  agent_radius: 0 # Radius of the agent
  last_scope: 1  # The last scope
  goal_sampling_rate: 0.2  # Goal sampling rate
  a_star_max_iter: 50000  # Maximum number of iterations
  rrt_star_max_iter: 3000  # Maximum number of iterations
  extend_length: 1  # Extension length
  consider_range: 3  # A range parameter, specific meaning depends on context
  stair_sample_step: 2  # The step size for stair sampling

llms:
  azure: false
  model_name: "gpt-4o" # gpt-4o-mini
  api_key: "sk-uxafF08zHYhVtHbw570c530d266847B7AfFcF04cBc5b60F3"
  api_url: "https://api.openai120.com/v1/chat/completions"
  image_detail: "high" # auto is by-default. low: 512x512. high: 768x2000.
  max_tokens: 2048
  system_prompt_file: "vln/src/llm/prompts/system_prompt.txt"
  user_prompt_file: "vln/src/llm/prompts/user_prompt.txt"
  interactive: true
  add_history: true

  map_grid_num: 30 # for map visualization