datasets:
  base_data_dir: "../VLN/VLNCE/R2R_VLNCE_v1-3"
  mp3d_data_dir: "../Matterport3D/data/v1/scans"
  mp3d_category_file: "vln/data/mappings/category_mapping.tsv"
  mp3d_mpcat40_file: "vln/data/mappings/mpcat40.tsv"
  splits:
    - val_seen
    # - train
    # - val_unseen
    # - test

settings:
  batch_size: 1
  action: "move_along_path"
  check_and_reset_robot: true

robots:
  - name: "CylinderRobot"
    z_offset: 0.7 # !!!
  - name: "HumanoidRobot"
    z_offset: 1.05 # !!!
  
maps:
  robot_z: [0.2, 1.7]  # Robot's height range on the Z-axis
  global_robot_z: [0, 1.7]
  robot_radius: 0.1 # Robot's radius
  voxel_size: 0.05  # Size of a voxel
  quadtree_config:
    width: 25 # Quadtree map size
    height: 25
    global_width: 30 # for global map
    global_height: 30
    max_depth: 10  # Maximum depth of the quadtree
    threshold: 1  # Threshold for node splitting  
    
planners:
  agent_radius: 0.25 # Radius of the agent
  last_scope: 1  # The last scope
  goal_sampling_rate: 0.2  # Goal sampling rate
  max_iter: 2000  # Maximum number of iterations
  extend_length: 1  # Extension length
  consider_range: 5  # A range parameter, specific meaning depends on context