simulator:
  physics_dt: 1/240
  rendering_dt: 1/240

tasks:
- type: "SingleInferenceTask"
  name: "cy_vlnce"
  scene_asset_path: ""
  scene_scale: [1, 1, 1]
  env_num: 1
  offset_size: 0.0
  robots:
  - name: cy
    prim_path: "/CY"
    type: "CylinderRobot"
    position: [0, 0, 0]
    scale: [1, 1, 1]
    orientation: [0,0,0,0]
    sensor_params:
    - name: "camera_tp"
      enable: true
      size: [512, 512]
    - name: "camera_front"
      enable: true
      size: [512, 512]
    - name: "camera_behind"
      enable: true
      size: [512, 512]
    - name: "camera_left"
      enable: true
      size: [512, 512]
    - name: "camera_right"
      enable: true
      size: [512, 512]

datasets:
  - name: "vlnce"
    base_data_dir: "VLN/VLNCE/R2R_VLNCE_v1-3"
    mp3d_data_dir: "Matterport3D/data/v1/scans"
