simulator:
  physics_dt: 1/240
  rendering_dt: 1/240

tasks:
- type: "SingleInferenceTask"
  name: "h1_house"
  # scene_asset_path: GRUtopia/assets/scenes/demo_house/demo_house.usd
  scene_asset_path: assets/robots/h1/simple_plane.usd
  # scene_asset_path : assets/robots/h1/naive_ground_plane.usd
  scene_scale: [0.01, 0.01, 0.01]
  env_num: 1
  offset_size: 1.0
  robots:
  - name: h1
    prim_path: "/World/h1"
    type: "HumanoidRobot"
    # position: [5.58, -0.77, 1.05]
    position: [0,0,1.06]
    scale: [1, 1, 1]
    controller_params:
    - name: "move_by_speed"
    - name: "joint_controller"
    - name: "move_to_point"
    - name: "move_along_path"
    - name: "rotate"
    - name: "move_with_keyboard"
    # - name: "web_chat"
    - name: "stand_still"
    sensor_params:
    # - name: "camera"
    #   enable: false
    # - name: "tp_camera"
    #   enable: false
      - name: "pano_camera_0"
        enable: true
        size: [256, 256]
